spring.application.name=ServiceRegistry
server.port=8761

# server should not register itself
eureka.client.register-with-eureka=false

#server should not fetch registry
eureka.client.fetch-registry=false