spring.application.name=BookStore-Security

spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_db2
spring.datasource.username=postgres
spring.datasource.password=Login@630

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=hklPa2OEkpESeYh0Yezj+LgnYvzOpQ1lBf2s1MBUCgQ=
jwt.expiration=86400000

cors.allowed-origins=http://localhost:3000, http://localhost:4200