spring.application.name=DoctorService

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3


